[VIDEO]
input_video = data/recordings/trimmed_4.bag
use_realsense = true
output_video = 
enable_auxiliary_display = false
smoothing_factor = 0.2
max_fps = 0 ; Set to 0 to turn off.

[SYSTEM]
model_path = models/YOLOv11s-02-09-99e.engine
enable_logging = false

[FRONTEND]
; Don't know if this is needed
layout = 