# Dcokerfile.dev (for amd64)

FROM ultralytics/ultralytics:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1-mesa-glx \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libfontconfig1 \
        libice6 \
        libjpeg-dev \
        zlib1g-dev \
        libpng-dev \
        libgtk-3-dev \
        pkg-config \
    && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/cv4gt-repo

